package com.github.satori87.gdx.webrtc.ios.bindings;

import org.robovm.apple.foundation.NSArray;
import org.robovm.apple.foundation.NSObject;
import org.robovm.objc.annotation.Method;

/**
 * RoboVM Java adapter for the Objective-C {@code RTCPeerConnectionDelegate} protocol
 * from Apple's WebRTC.framework.
 *
 * <p>This class provides no-op default implementations for every delegate method.
 * Subclass it and override only the callbacks you need. The most commonly used
 * callbacks for gdx-webrtc are:</p>
 * <ul>
 *   <li>{@link #didGenerateIceCandidate} -- forward ICE candidates to the signaling server</li>
 *   <li>{@link #didOpenDataChannel} -- register incoming data channels</li>
 *   <li>{@link #didChangeConnectionState} -- track peer connection lifecycle</li>
 * </ul>
 *
 * <p>Each method is annotated with the corresponding Objective-C selector so that
 * RoboVM can dispatch native delegate callbacks into Java.</p>
 *
 * @see RTCPeerConnection
 * @see RTCPeerConnectionFactory#createPeerConnection(RTCConfiguration, RTCMediaConstraints, RTCPeerConnectionDelegate)
 */
public class RTCPeerConnectionDelegate extends NSObject {

    /**
     * Called when the peer connection's signaling state changes.
     *
     * @param peerConnection the peer connection whose state changed
     * @param newState       the new signaling state as a native enum ordinal
     */
    @Method(selector = "peerConnection:didChangeSignalingState:")
    public void didChangeSignalingState(RTCPeerConnection peerConnection, int newState) {}

    /**
     * Called when a remote media stream is added to the peer connection.
     *
     * @param peerConnection the peer connection that received the stream
     * @param stream         the added media stream (as a raw NSObject)
     */
    @Method(selector = "peerConnection:didAddStream:")
    public void didAddStream(RTCPeerConnection peerConnection, NSObject stream) {}

    /**
     * Called when a remote media stream is removed from the peer connection.
     *
     * @param peerConnection the peer connection that lost the stream
     * @param stream         the removed media stream (as a raw NSObject)
     */
    @Method(selector = "peerConnection:didRemoveStream:")
    public void didRemoveStream(RTCPeerConnection peerConnection, NSObject stream) {}

    /**
     * Called when the peer connection determines that negotiation is needed.
     *
     * @param peerConnection the peer connection requesting negotiation
     */
    @Method(selector = "peerConnectionShouldNegotiate:")
    public void peerConnectionShouldNegotiate(RTCPeerConnection peerConnection) {}

    /**
     * Called when the ICE connection state changes (e.g., checking, connected, failed).
     *
     * @param peerConnection the peer connection whose ICE connection state changed
     * @param newState       the new ICE connection state as a native enum ordinal
     */
    @Method(selector = "peerConnection:didChangeIceConnectionState:")
    public void didChangeIceConnectionState(RTCPeerConnection peerConnection, int newState) {}

    /**
     * Called when the ICE gathering state changes (e.g., new, gathering, complete).
     *
     * @param peerConnection the peer connection whose ICE gathering state changed
     * @param newState       the new ICE gathering state as a native enum ordinal
     */
    @Method(selector = "peerConnection:didChangeIceGatheringState:")
    public void didChangeIceGatheringState(RTCPeerConnection peerConnection, int newState) {}

    /**
     * Called when a new ICE candidate has been generated by the local peer connection.
     * The candidate should be sent to the remote peer via the signaling channel.
     *
     * @param peerConnection the peer connection that generated the candidate
     * @param candidate      the newly generated ICE candidate
     */
    @Method(selector = "peerConnection:didGenerateIceCandidate:")
    public void didGenerateIceCandidate(RTCPeerConnection peerConnection, RTCIceCandidate candidate) {}

    /**
     * Called when one or more ICE candidates have been removed.
     *
     * @param peerConnection the peer connection from which candidates were removed
     * @param candidates     the array of removed ICE candidates
     */
    @Method(selector = "peerConnection:didRemoveIceCandidates:")
    public void didRemoveIceCandidates(RTCPeerConnection peerConnection, NSArray<?> candidates) {}

    /**
     * Called when a remote peer opens a data channel on this peer connection.
     * This is the entry point for receiving data channels created by the remote side.
     *
     * @param peerConnection the peer connection that received the data channel
     * @param dataChannel    the newly opened data channel
     */
    @Method(selector = "peerConnection:didOpenDataChannel:")
    public void didOpenDataChannel(RTCPeerConnection peerConnection, RTCDataChannel dataChannel) {}

    /**
     * Called when the overall peer connection state changes.
     * The {@code newState} values correspond to the constants in {@link RTCPeerConnectionState}.
     *
     * @param peerConnection the peer connection whose state changed
     * @param newState       the new connection state as a {@link RTCPeerConnectionState} ordinal
     */
    @Method(selector = "peerConnection:didChangeConnectionState:")
    public void didChangeConnectionState(RTCPeerConnection peerConnection, int newState) {}
}
